name: flutter_payment
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.5.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^11.0.0
  get_it: ^8.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-semiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

flutter_assets:
  assets_path: assets/icons/
  output_path: lib/core/
  filename: app_icons.dart
